### ISSUE TITLE
TypeError: Cannot read property 'Add' of undefined

### ISSUE THREAD

**Issue by samirbr** [ncsoft/React-UMG#2]
I'm using Unreal.js ```zThirdPerson.js``` example. It runs perfect and smooth.
When I run the following code snipped from React-UMG documentation.

```
const React = require('react');
const ReactUMG = require('react-umg');

class MyComponent extends React.Component {
  constructor(props, context) {
    super(props, context);

    this.state = {
      text: 'MyComponent',
    };
  }

  OnTextChanged(value) {
    this.setState({
      text: value,
    });
  }

  static attach() {
    this.widget = ReactUMG.wrap(<MyComponent />);
    this.widget.AddToViewport();

    return () => {
      this.widget.RemoveFromViewport();
    };
  }

  render() {
    return (
      <div>
        <uEditableTextBox
          Text={this.state.text}
          OnTextChanged={value => this.OnTextChanged(value)} />
        <text Text={this.state.text} />
      </div>
    );
  }
}

MyComponent.attach();

```

I get the following error.

```
Error: Game/Content/Scripts/node_modules/react-umg/src/ReactUMGMount.js:146: TypeError: Cannot read property 'Add' of undefined
Error: TypeError: Cannot read property 'Add' of undefined
Error:     at Object.render (Game/Content/Scripts/node_modules/react-umg/src/ReactUMGMount.js:146:26)
Error:     at Function.attach (Game/Content/Scripts/components/MyComponent.js:36:38)
```

I pushed a [PR](https://github.com/ncsoft/React-UMG/pull/1) to fix this error.

Thanks

**Comment by crocuis** [comment]
Closed
